spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 170804
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
api:
  prefix: api/v1